
/*
  # Create system user and seed predefined templates/macros

  ## Overview
  1. Creates a system user in auth.users for system-level templates and macros
  2. Seeds 20 predefined radiology report templates across all modalities
  3. Seeds 10 system-level macros for common findings
  4. Adds RLS policies for all authenticated users to read system resources

  ## Templates (20)
  CT: Chest Normal, Lung Cancer, PE, Abdomen Normal, Kidney Stone, Head Normal, Stroke
  MRI: Brain Normal, MS
  X-Ray: Chest Normal, Pneumonia, Rib Fracture
  Ultrasound: Abdomen Normal, Kidney Stone, Gallstones, Pelvis Normal, Thyroid Normal, Obstetric 1st Tri
  PET-CT: Oncology Staging
  Mammography: Normal

  ## Macros (10)
  US: /us-normal-abd, /us-normal-kidney, /us-gallstones, /us-kidney-stone, /us-normal-thyroid, /us-normal-pelvis
  CT: /ct-normal-chest, /ct-normal-abd, /ct-normal-brain
  MRI: /mri-normal-brain
*/

-- Create system user in auth.users
INSERT INTO auth.users (
  id, instance_id, aud, role, email, encrypted_password, email_confirmed_at,
  created_at, updated_at, confirmation_token, email_change, recovery_token
) VALUES (
  '00000000-0000-0000-0000-000000000000',
  '00000000-0000-0000-0000-000000000000',
  'authenticated',
  'authenticated',
  'system@radai.internal',
  extensions.crypt(
  'system-placeholder-not-for-login',
  extensions.gen_salt('bf')
),
  now(),
  now(),
  now(),
  '',
  '',
  ''
) ON CONFLICT (id) DO NOTHING;

-- Create system profile
INSERT INTO profiles (id, name, role, specialty) VALUES
  ('00000000-0000-0000-0000-000000000000', 'System', 'system', 'general')
ON CONFLICT (id) DO NOTHING;

-- RLS policies for system resources
CREATE POLICY "Authenticated users can read system templates"
  ON templates FOR SELECT
  TO authenticated
  USING (user_id = '00000000-0000-0000-0000-000000000000');

CREATE POLICY "Authenticated users can read system macros"
  ON macros FOR SELECT
  TO authenticated
  USING (user_id = '00000000-0000-0000-0000-000000000000');

-- ============ TEMPLATES ============

INSERT INTO templates (user_id, name, description, scan_type, structure, conditions, is_default, usage_count) VALUES
('00000000-0000-0000-0000-000000000000', 'CT Chest - Normal', 'Standard normal CT chest report format', 'CT Chest',
'[{"id":"s1","label":"Technique","placeholder":"Helical CT of the chest was performed with intravenous contrast...","required":true,"type":"text"},{"id":"s2","label":"Clinical Indication","placeholder":"Reason for examination...","required":true,"type":"text"},{"id":"s3","label":"Findings","placeholder":"The lungs are clear bilaterally without focal consolidation, pleural effusion, or pneumothorax...","required":true,"type":"text"},{"id":"s4","label":"Impression","placeholder":"1. No acute cardiopulmonary abnormality.","required":true,"type":"text"}]'::jsonb, '[]'::jsonb, true, 0),

('00000000-0000-0000-0000-000000000000', 'CT Chest - Pulmonary Nodule / Lung Cancer', 'Comprehensive format for pulmonary nodule or lung cancer with measurement and staging', 'CT Chest',
'[{"id":"s1","label":"Technique","placeholder":"Helical CT of the chest was performed with intravenous contrast...","required":true,"type":"text"},{"id":"s2","label":"Clinical Indication","placeholder":"Known or suspected pulmonary nodule...","required":true,"type":"text"},{"id":"s3","label":"Nodule Characteristics","placeholder":"Location, size, morphology, attenuation, margins...","required":true,"type":"text"},{"id":"s4","label":"Findings - Lungs","placeholder":"Description of pulmonary parenchyma including nodule details...","required":true,"type":"text"},{"id":"s5","label":"Findings - Mediastinum","placeholder":"Mediastinal and hilar lymph nodes...","required":true,"type":"text"},{"id":"s6","label":"Findings - Other","placeholder":"Pleura, pericardium, chest wall, upper abdomen...","required":false,"type":"text"},{"id":"s7","label":"Staging (if malignancy)","placeholder":"T: , N: , M: , Stage:","required":false,"type":"text"},{"id":"s8","label":"Impression","placeholder":"1. Pulmonary nodule... 2. Recommendations...","required":true,"type":"text"}]'::jsonb,
'[{"id":"c1","trigger_keyword":"lung nodule","add_section":"Nodule Characteristics","section_content":"A pulmonary nodule is identified. Size, location, morphology, and attenuation characteristics are described below. Lung-RADS classification recommended."},{"id":"c2","trigger_keyword":"lung cancer","add_section":"Staging (if malignancy)","section_content":"TNM staging assessment based on current imaging findings. Primary tumor: [T]. Regional lymph nodes: [N]. Distant metastasis: [M]."},{"id":"c3","trigger_keyword":"metastasis","add_section":"Staging (if malignancy)","section_content":"Evidence of metastatic disease. Sites involved: [specify]."}]'::jsonb, false, 0),

('00000000-0000-0000-0000-000000000000', 'CT Chest - Pulmonary Embolism', 'Format for CT pulmonary angiography with PE reporting', 'CT Chest',
'[{"id":"s1","label":"Technique","placeholder":"CT pulmonary angiography was performed following intravenous administration of contrast...","required":true,"type":"text"},{"id":"s2","label":"Clinical Indication","placeholder":"Suspected pulmonary embolism...","required":true,"type":"text"},{"id":"s3","label":"Pulmonary Arteries","placeholder":"Description of filling defects, location, and extent...","required":true,"type":"text"},{"id":"s4","label":"Findings - Cardiac","placeholder":"Right ventricular size, interventricular septum, RV/LV ratio...","required":true,"type":"text"},{"id":"s5","label":"Findings - Lungs","placeholder":"Parenchymal abnormalities, infarction, effusions...","required":false,"type":"text"},{"id":"s6","label":"Impression","placeholder":"1. Acute pulmonary embolism...","required":true,"type":"text"}]'::jsonb,
'[{"id":"c1","trigger_keyword":"pulmonary embolism","add_section":"Pulmonary Arteries","section_content":"Filling defect(s) identified in the pulmonary arterial system. Location and extent to be specified."},{"id":"c2","trigger_keyword":"right heart strain","add_section":"Findings - Cardiac","section_content":"Signs of right heart strain: RV/LV ratio >1.0, interventricular septum bowing, reflux of contrast into IVC/hepatic veins."}]'::jsonb, false, 0),

('00000000-0000-0000-0000-000000000000', 'CT Abdomen/Pelvis - Normal', 'Standard normal CT abdomen and pelvis report', 'CT Abdomen/Pelvis',
'[{"id":"s1","label":"Technique","placeholder":"Helical CT of the abdomen and pelvis was performed with intravenous and oral contrast...","required":true,"type":"text"},{"id":"s2","label":"Clinical Indication","placeholder":"Reason for examination...","required":true,"type":"text"},{"id":"s3","label":"Findings - Liver","placeholder":"The liver is normal in size and attenuation without focal lesion...","required":true,"type":"text"},{"id":"s4","label":"Findings - Biliary","placeholder":"The gallbladder is normal. No biliary dilatation...","required":true,"type":"text"},{"id":"s5","label":"Findings - Pancreas","placeholder":"The pancreas is normal without focal lesion or ductal dilatation...","required":true,"type":"text"},{"id":"s6","label":"Findings - Spleen","placeholder":"The spleen is normal in size...","required":true,"type":"text"},{"id":"s7","label":"Findings - Kidneys","placeholder":"The kidneys enhance symmetrically without focal lesion or hydronephrosis...","required":true,"type":"text"},{"id":"s8","label":"Findings - Bowel","placeholder":"The bowel is normal in caliber and enhancement...","required":false,"type":"text"},{"id":"s9","label":"Findings - Other","placeholder":"No free fluid, lymphadenopathy, or osseous abnormality...","required":false,"type":"text"},{"id":"s10","label":"Impression","placeholder":"1. No acute abdominal or pelvic abnormality.","required":true,"type":"text"}]'::jsonb, '[]'::jsonb, true, 0),

('00000000-0000-0000-0000-000000000000', 'CT Abdomen/Pelvis - Kidney Stone', 'Format for renal calculus reporting with measurements and hydronephrosis', 'CT Abdomen/Pelvis',
'[{"id":"s1","label":"Technique","placeholder":"Non-contrast CT of the abdomen and pelvis (stone protocol)...","required":true,"type":"text"},{"id":"s2","label":"Clinical Indication","placeholder":"Flank pain, suspected nephrolithiasis...","required":true,"type":"text"},{"id":"s3","label":"Findings - Kidneys","placeholder":"Right kidney: [stone size, location, hydronephrosis]. Left kidney: [stone size, location, hydronephrosis]...","required":true,"type":"text"},{"id":"s4","label":"Findings - Ureters","placeholder":"Ureteral calculi, location and size...","required":true,"type":"text"},{"id":"s5","label":"Findings - Bladder","placeholder":"Bladder status...","required":false,"type":"text"},{"id":"s6","label":"Findings - Other","placeholder":"Other abdominal findings...","required":false,"type":"text"},{"id":"s7","label":"Impression","placeholder":"1. Calculus identified... Size, location, hydronephrosis status...","required":true,"type":"text"}]'::jsonb,
'[{"id":"c1","trigger_keyword":"kidney stone","add_section":"Findings - Kidneys","section_content":"Renal calculus identified. Size: [X] mm. Location: [right/left kidney, specific location]. Associated hydronephrosis: [present/absent]."},{"id":"c2","trigger_keyword":"hydronephrosis","add_section":"Findings - Ureters","section_content":"Hydronephrosis noted. Assess for level of obstruction - ureteral calculus vs. extrinsic compression."}]'::jsonb, false, 0),

('00000000-0000-0000-0000-000000000000', 'CT Head - Normal', 'Standard normal non-contrast CT head report', 'CT Head',
'[{"id":"s1","label":"Technique","placeholder":"Non-contrast CT of the head was performed...","required":true,"type":"text"},{"id":"s2","label":"Clinical Indication","placeholder":"Reason for examination...","required":true,"type":"text"},{"id":"s3","label":"Findings","placeholder":"No intracranial hemorrhage, mass effect, or midline shift. The gray-white matter differentiation is preserved. The ventricles and sulci are normal in size and configuration. No acute territorial infarction. The basal cisterns are patent. The calvarium and skull base are intact.","required":true,"type":"text"},{"id":"s4","label":"Impression","placeholder":"1. No acute intracranial abnormality.","required":true,"type":"text"}]'::jsonb, '[]'::jsonb, true, 0),

('00000000-0000-0000-0000-000000000000', 'CT Head - Acute Stroke', 'Format for acute stroke CT head with ASPECTS scoring', 'CT Head',
'[{"id":"s1","label":"Technique","placeholder":"Non-contrast CT of the head. CTA head/neck if applicable...","required":true,"type":"text"},{"id":"s2","label":"Clinical Indication","placeholder":"Acute neurological deficit, suspected stroke...","required":true,"type":"text"},{"id":"s3","label":"Findings - Parenchyma","placeholder":"ASPECTS score, early ischemic changes, hemorrhage assessment...","required":true,"type":"text"},{"id":"s4","label":"Findings - Vessels","placeholder":"CTA findings if performed...","required":false,"type":"text"},{"id":"s5","label":"Findings - Other","placeholder":"Ventricles, cisterns, calvarium...","required":false,"type":"text"},{"id":"s6","label":"Impression","placeholder":"1. Findings consistent with acute stroke... ASPECTS: X/10...","required":true,"type":"text"}]'::jsonb,
'[{"id":"c1","trigger_keyword":"stroke","add_section":"Findings - Parenchyma","section_content":"Assess for early ischemic changes. ASPECTS scoring: [score]/10. Territory involved: [MCA/ACA/PCA]."},{"id":"c2","trigger_keyword":"hemorrhage","add_section":"Findings - Parenchyma","section_content":"Intracranial hemorrhage identified. Type: [intraparenchymal/subarachnoid/subdural/epidural]. Location: [specify]. Volume estimate: [X] mL."}]'::jsonb, false, 0),

('00000000-0000-0000-0000-000000000000', 'MRI Brain - Normal', 'Standard normal MRI brain report', 'MRI Brain',
'[{"id":"s1","label":"Technique","placeholder":"MRI of the brain including T1, T2, FLAIR, and DWI sequences with and without gadolinium...","required":true,"type":"text"},{"id":"s2","label":"Clinical Indication","placeholder":"Reason for examination...","required":true,"type":"text"},{"id":"s3","label":"Findings","placeholder":"No abnormal signal intensity on any sequence. No evidence of acute infarction on DWI. No enhancing lesion. The ventricles are normal. No mass effect or midline shift. The major intracranial flow voids are preserved. The paranasal sinuses and mastoid air cells are clear.","required":true,"type":"text"},{"id":"s4","label":"Impression","placeholder":"1. No acute intracranial abnormality. 2. Normal MRI of the brain.","required":true,"type":"text"}]'::jsonb, '[]'::jsonb, true, 0),

('00000000-0000-0000-0000-000000000000', 'MRI Brain - Multiple Sclerosis', 'Format for MS/demyelination MRI brain reporting', 'MRI Brain',
'[{"id":"s1","label":"Technique","placeholder":"MRI of the brain with and without gadolinium including T1, T2, FLAIR, DWI...","required":true,"type":"text"},{"id":"s2","label":"Clinical Indication","placeholder":"Known or suspected demyelinating disease...","required":true,"type":"text"},{"id":"s3","label":"Findings - White Matter","placeholder":"Periventricular, juxtacortical, infratentorial, spinal cord lesions...","required":true,"type":"text"},{"id":"s4","label":"Findings - Enhancement","placeholder":"Enhancing vs non-enhancing lesions...","required":true,"type":"text"},{"id":"s5","label":"Findings - Other","placeholder":"Brain volume, ventricles, sinuses...","required":false,"type":"text"},{"id":"s6","label":"Impression","placeholder":"1. White matter lesions consistent with demyelinating disease... 2. Comparison with prior: [stable/new/enlarged]","required":true,"type":"text"}]'::jsonb, '[]'::jsonb, false, 0),

('00000000-0000-0000-0000-000000000000', 'X-Ray Chest - Normal', 'Standard normal chest X-ray report', 'X-Ray Chest',
'[{"id":"s1","label":"Technique","placeholder":"PA and lateral views of the chest...","required":true,"type":"text"},{"id":"s2","label":"Clinical Indication","placeholder":"Reason for examination...","required":true,"type":"text"},{"id":"s3","label":"Findings","placeholder":"The lungs are clear bilaterally without focal consolidation, pleural effusion, or pneumothorax. The cardiac silhouette is within normal limits. The mediastinal contour is unremarkable. The osseous structures are intact.","required":true,"type":"text"},{"id":"s4","label":"Impression","placeholder":"1. No acute cardiopulmonary abnormality.","required":true,"type":"text"}]'::jsonb, '[]'::jsonb, true, 0),

('00000000-0000-0000-0000-000000000000', 'X-Ray Chest - Pneumonia', 'Format for pneumonia chest X-ray reporting', 'X-Ray Chest',
'[{"id":"s1","label":"Technique","placeholder":"PA and lateral views of the chest...","required":true,"type":"text"},{"id":"s2","label":"Clinical Indication","placeholder":"Suspected pneumonia, fever, cough...","required":true,"type":"text"},{"id":"s3","label":"Findings - Consolidation","placeholder":"Location, extent, pattern of consolidation...","required":true,"type":"text"},{"id":"s4","label":"Findings - Other","placeholder":"Pleural effusion, cardiomediastinal silhouette, osseous structures...","required":false,"type":"text"},{"id":"s5","label":"Impression","placeholder":"1. Consolidation in [location] consistent with pneumonia...","required":true,"type":"text"}]'::jsonb, '[]'::jsonb, false, 0),

('00000000-0000-0000-0000-000000000000', 'X-Ray Chest - Rib Fracture', 'Format for rib fracture chest X-ray reporting', 'X-Ray Chest',
'[{"id":"s1","label":"Technique","placeholder":"PA and lateral views of the chest...","required":true,"type":"text"},{"id":"s2","label":"Clinical Indication","placeholder":"Trauma, chest pain...","required":true,"type":"text"},{"id":"s3","label":"Findings - Osseous","placeholder":"Rib fractures: location, number, displacement...","required":true,"type":"text"},{"id":"s4","label":"Findings - Lungs","placeholder":"Pneumothorax, hemothorax, pulmonary contusion...","required":true,"type":"text"},{"id":"s5","label":"Impression","placeholder":"1. Rib fracture(s)... 2. Complications if any...","required":true,"type":"text"}]'::jsonb, '[]'::jsonb, false, 0),

('00000000-0000-0000-0000-000000000000', 'Ultrasound Abdomen - Normal', 'Standard normal abdominal ultrasound report', 'Ultrasound Abdomen',
'[{"id":"s1","label":"Technique","placeholder":"Ultrasound of the abdomen was performed with the patient in supine position...","required":true,"type":"text"},{"id":"s2","label":"Clinical Indication","placeholder":"Reason for examination...","required":true,"type":"text"},{"id":"s3","label":"Findings - Liver","placeholder":"The liver is normal in size and echotexture without focal lesion. No intrahepatic biliary dilatation. Portal vein is patent with hepatopetal flow.","required":true,"type":"text"},{"id":"s4","label":"Findings - Gallbladder","placeholder":"The gallbladder is normal in size, wall thickness, and echotexture. No gallstones, sludge, or pericholecystic fluid.","required":true,"type":"text"},{"id":"s5","label":"Findings - Pancreas","placeholder":"The pancreas is normal in echotexture without focal lesion or ductal dilatation.","required":true,"type":"text"},{"id":"s6","label":"Findings - Spleen","placeholder":"The spleen is normal in size measuring [X] cm. No focal lesion.","required":true,"type":"text"},{"id":"s7","label":"Findings - Kidneys","placeholder":"Right kidney measures [X] cm, left kidney measures [X] cm. Both kidneys show normal cortical thickness and echogenicity. No hydronephrosis, calculus, or mass.","required":true,"type":"text"},{"id":"s8","label":"Findings - Aorta","placeholder":"The abdominal aorta is normal in caliber measuring [X] cm.","required":false,"type":"text"},{"id":"s9","label":"Impression","placeholder":"1. Normal abdominal ultrasound. 2. No evidence of solid organ abnormality, biliary pathology, or hydronephrosis.","required":true,"type":"text"}]'::jsonb, '[]'::jsonb, true, 0),

('00000000-0000-0000-0000-000000000000', 'Ultrasound Abdomen - Kidney Stone', 'Format for renal calculus ultrasound reporting', 'Ultrasound Abdomen',
'[{"id":"s1","label":"Technique","placeholder":"Ultrasound of the abdomen with focus on the urinary tract...","required":true,"type":"text"},{"id":"s2","label":"Clinical Indication","placeholder":"Flank pain, hematuria, suspected nephrolithiasis...","required":true,"type":"text"},{"id":"s3","label":"Findings - Right Kidney","placeholder":"Right kidney: size, cortical thickness, echogenicity, calculus (size, location), hydronephrosis...","required":true,"type":"text"},{"id":"s4","label":"Findings - Left Kidney","placeholder":"Left kidney: size, cortical thickness, echogenicity, calculus (size, location), hydronephrosis...","required":true,"type":"text"},{"id":"s5","label":"Findings - Bladder","placeholder":"Urinary bladder: wall thickness, capacity, calculi, debris...","required":true,"type":"text"},{"id":"s6","label":"Findings - Other","placeholder":"Liver, gallbladder, pancreas, spleen...","required":false,"type":"text"},{"id":"s7","label":"Impression","placeholder":"1. [Right/Left/Bilateral] renal calculus measuring [X] mm. 2. [Hydronephrosis present/absent]. 3. Recommendations...","required":true,"type":"text"}]'::jsonb,
'[{"id":"c1","trigger_keyword":"kidney stone","add_section":"Findings - Right Kidney","section_content":"Renal calculus identified. Size: [X] mm. Location: [upper/mid/lower pole]. Echogenic focus with posterior acoustic shadowing. Associated hydronephrosis: [present/absent, grade]."},{"id":"c2","trigger_keyword":"hydronephrosis","add_section":"Findings - Right Kidney","section_content":"Hydronephrosis identified. Grade: [mild/moderate/severe]. Assess for level of obstruction."}]'::jsonb, false, 0),

('00000000-0000-0000-0000-000000000000', 'Ultrasound Abdomen - Gallstones / Cholecystitis', 'Format for gallbladder pathology ultrasound reporting', 'Ultrasound Abdomen',
'[{"id":"s1","label":"Technique","placeholder":"Ultrasound of the abdomen with focus on the gallbladder and biliary tree...","required":true,"type":"text"},{"id":"s2","label":"Clinical Indication","placeholder":"Right upper quadrant pain, suspected cholecystitis...","required":true,"type":"text"},{"id":"s3","label":"Findings - Gallbladder","placeholder":"Gallbladder size, wall thickness, stones, sludge, Murphy sign, pericholecystic fluid...","required":true,"type":"text"},{"id":"s4","label":"Findings - Biliary Tree","placeholder":"Common bile duct diameter, intrahepatic ducts...","required":true,"type":"text"},{"id":"s5","label":"Findings - Other","placeholder":"Liver, pancreas, spleen, kidneys...","required":false,"type":"text"},{"id":"s6","label":"Impression","placeholder":"1. Cholelithiasis / Cholecystitis... 2. Biliary dilatation if present...","required":true,"type":"text"}]'::jsonb,
'[{"id":"c1","trigger_keyword":"cholecystitis","add_section":"Findings - Gallbladder","section_content":"Findings concerning for cholecystitis: gallbladder wall thickening >3mm, pericholecystic fluid, positive sonographic Murphy sign, gallstones."}]'::jsonb, false, 0),

('00000000-0000-0000-0000-000000000000', 'Ultrasound Pelvis - Normal (Female)', 'Standard normal female pelvic ultrasound report', 'Ultrasound Pelvis',
'[{"id":"s1","label":"Technique","placeholder":"Transabdominal and transvaginal ultrasound of the pelvis was performed...","required":true,"type":"text"},{"id":"s2","label":"Clinical Indication","placeholder":"Reason for examination...","required":true,"type":"text"},{"id":"s3","label":"Findings - Uterus","placeholder":"The uterus is normal in size and echotexture. Endometrial thickness: [X] mm. No focal myometrial lesion.","required":true,"type":"text"},{"id":"s4","label":"Findings - Ovaries","placeholder":"Right ovary: [size, follicles]. Left ovary: [size, follicles]. No adnexal mass.","required":true,"type":"text"},{"id":"s5","label":"Findings - Cul-de-sac","placeholder":"No free fluid in the cul-de-sac.","required":false,"type":"text"},{"id":"s6","label":"Impression","placeholder":"1. Normal pelvic ultrasound. 2. No adnexal mass or free fluid.","required":true,"type":"text"}]'::jsonb, '[]'::jsonb, true, 0),

('00000000-0000-0000-0000-000000000000', 'Ultrasound Thyroid - Normal', 'Standard normal thyroid ultrasound report', 'Ultrasound Thyroid',
'[{"id":"s1","label":"Technique","placeholder":"Ultrasound of the thyroid gland was performed...","required":true,"type":"text"},{"id":"s2","label":"Clinical Indication","placeholder":"Reason for examination...","required":true,"type":"text"},{"id":"s3","label":"Findings - Thyroid","placeholder":"The thyroid gland is normal in size and echotexture. Right lobe: [X] x [X] x [X] cm. Left lobe: [X] x [X] x [X] cm. Isthmus: [X] mm. No focal nodule or cyst.","required":true,"type":"text"},{"id":"s4","label":"Findings - Adjacent","placeholder":"No significant cervical lymphadenopathy.","required":false,"type":"text"},{"id":"s5","label":"Impression","placeholder":"1. Normal thyroid ultrasound. 2. No thyroid nodule or abnormality.","required":true,"type":"text"}]'::jsonb, '[]'::jsonb, true, 0),

('00000000-0000-0000-0000-000000000000', 'Ultrasound Obstetric - First Trimester', 'First trimester obstetric ultrasound report format', 'Ultrasound Obstetric',
'[{"id":"s1","label":"Technique","placeholder":"Transabdominal (and transvaginal if applicable) ultrasound...","required":true,"type":"text"},{"id":"s2","label":"Clinical Indication","placeholder":"Dating, viability, bleeding...","required":true,"type":"text"},{"id":"s3","label":"Findings - Gestational Sac","placeholder":"Intrauterine gestational sac present. Mean sac diameter: [X] mm. Location: [fundal/mid/lower]","required":true,"type":"text"},{"id":"s4","label":"Findings - Fetus","placeholder":"Crown-rump length: [X] mm. Fetal heart rate: [X] bpm. Fetal number: [single/twins]","required":true,"type":"text"},{"id":"s5","label":"Findings - Adnexa","placeholder":"Right adnexa: [normal/mass]. Left adnexa: [normal/mass]. Corpus luteum: [present/absent]","required":false,"type":"text"},{"id":"s6","label":"Estimated GA","placeholder":"By CRL: [X] weeks [X] days. By LMP: [X] weeks [X] days. EDD: [date]","required":true,"type":"text"},{"id":"s7","label":"Impression","placeholder":"1. Intrauterine pregnancy. 2. Viability: [viable/non-viable]. 3. Estimated GA: [X] weeks [X] days.","required":true,"type":"text"}]'::jsonb, '[]'::jsonb, false, 0),

('00000000-0000-0000-0000-000000000000', 'PET-CT - Oncology Staging', 'Format for PET-CT oncology staging and restaging', 'PET-CT',
'[{"id":"s1","label":"Technique","placeholder":"FDG PET-CT was performed from skull base to mid-thigh...","required":true,"type":"text"},{"id":"s2","label":"Clinical Indication","placeholder":"Known malignancy, staging/restaging...","required":true,"type":"text"},{"id":"s3","label":"Findings - Primary","placeholder":"Primary site, size, SUVmax...","required":true,"type":"text"},{"id":"s4","label":"Findings - Nodal","placeholder":"Regional and distant lymph nodes with FDG uptake...","required":true,"type":"text"},{"id":"s5","label":"Findings - Metastatic","placeholder":"Distant metastatic sites...","required":true,"type":"text"},{"id":"s6","label":"Findings - Incidental","placeholder":"Incidental FDG uptake, non-malignant findings...","required":false,"type":"text"},{"id":"s7","label":"Impression","placeholder":"1. Staging assessment... 2. Comparison with prior if applicable...","required":true,"type":"text"}]'::jsonb, '[]'::jsonb, false, 0),

('00000000-0000-0000-0000-000000000000', 'Mammography - Normal', 'Standard normal mammography report with BI-RADS', 'Mammography',
'[{"id":"s1","label":"Technique","placeholder":"Bilateral digital screening mammography...","required":true,"type":"text"},{"id":"s2","label":"Clinical Indication","placeholder":"Screening mammography...","required":true,"type":"text"},{"id":"s3","label":"Findings - Right","placeholder":"Breast composition, masses, calcifications, architectural distortion...","required":true,"type":"text"},{"id":"s4","label":"Findings - Left","placeholder":"Breast composition, masses, calcifications, architectural distortion...","required":true,"type":"text"},{"id":"s5","label":"BI-RADS","placeholder":"BI-RADS Category 1 - Negative","required":true,"type":"text"},{"id":"s6","label":"Impression","placeholder":"1. BI-RADS 1: Negative. Routine screening recommended in 1 year.","required":true,"type":"text"}]'::jsonb, '[]'::jsonb, true, 0);

-- ============ SYSTEM MACROS ============

INSERT INTO macros (user_id, trigger, expansion, category, description, usage_count) VALUES
('00000000-0000-0000-0000-000000000000', '/us-normal-abd', 'The liver is normal in size and echotexture without focal lesion. No intrahepatic biliary dilatation. The gallbladder is normal with no gallstones or wall thickening. The pancreas is normal in echotexture. The spleen is normal in size. Both kidneys show normal cortical thickness and echogenicity without hydronephrosis or calculus. The abdominal aorta is normal in caliber. No free fluid.', 'abdomen', 'Normal abdominal ultrasound', 0),
('00000000-0000-0000-0000-000000000000', '/us-normal-kidney', 'Both kidneys are normal in size with maintained cortical thickness and echogenicity. No hydronephrosis, calculus, or mass lesion identified. Corticomedullary differentiation is maintained.', 'abdomen', 'Normal kidneys ultrasound', 0),
('00000000-0000-0000-0000-000000000000', '/us-gallstones', 'Multiple echogenic foci within the gallbladder lumen demonstrating posterior acoustic shadowing, consistent with gallstones. Gallbladder wall thickness is within normal limits. No pericholecystic fluid. No sonographic Murphy sign.', 'abdomen', 'Gallstones finding', 0),
('00000000-0000-0000-0000-000000000000', '/us-kidney-stone', 'An echogenic focus with posterior acoustic shadowing is identified within the [right/left] kidney, measuring [X] mm, consistent with a calculus. [No/Minimal/Mild/Moderate/Severe] hydronephrosis is noted on the [right/left].', 'abdomen', 'Kidney stone finding', 0),
('00000000-0000-0000-0000-000000000000', '/us-normal-thyroid', 'The thyroid gland is normal in size and echotexture. No focal nodule or cyst identified. The isthmus is normal in thickness. No significant cervical lymphadenopathy.', 'general', 'Normal thyroid ultrasound', 0),
('00000000-0000-0000-0000-000000000000', '/us-normal-pelvis', 'The uterus is normal in size and echotexture. The endometrial thickness is within normal limits. Both ovaries are normal in size with normal follicular pattern. No adnexal mass or free fluid in the cul-de-sac.', 'general', 'Normal pelvic ultrasound', 0),
('00000000-0000-0000-0000-000000000000', '/ct-normal-chest', 'The lungs are clear bilaterally without focal consolidation, pleural effusion, or pneumothorax. The cardiac silhouette is within normal limits. The mediastinal and hilar contours are unremarkable. No pathologic lymphadenopathy. The thyroid gland is normal. The upper abdominal structures are unremarkable. The osseous structures are intact without acute fracture or suspicious lesion.', 'chest', 'Normal CT chest', 0),
('00000000-0000-0000-0000-000000000000', '/ct-normal-abd', 'The liver is normal in size and attenuation without focal lesion. No intrahepatic or extrahepatic biliary dilatation. The gallbladder is normal. The pancreas is normal without focal lesion or ductal dilatation. The spleen is normal in size. Both kidneys enhance symmetrically without focal lesion or hydronephrosis. No retroperitoneal or mesenteric lymphadenopathy. No free fluid or free air. The bowel is normal in caliber and enhancement. The osseous structures are intact.', 'abdomen', 'Normal CT abdomen/pelvis', 0),
('00000000-0000-0000-0000-000000000000', '/ct-normal-brain', 'No intracranial hemorrhage, mass effect, or midline shift. The gray-white matter differentiation is preserved. The ventricles and sulci are normal in size and configuration. No acute territorial infarction. The basal cisterns are patent. The calvarium and skull base are intact. No osseous abnormality.', 'neuro', 'Normal CT head', 0),
('00000000-0000-0000-0000-000000000000', '/mri-normal-brain', 'No abnormal signal intensity on any sequence. No evidence of acute infarction on DWI. No enhancing lesion following gadolinium administration. The ventricles are normal in size. No mass effect or midline shift. The major intracranial flow voids are preserved. The paranasal sinuses and mastoid air cells are clear. No abnormal meningeal enhancement.', 'neuro', 'Normal MRI brain', 0);
